<?xml version="1.0" encoding="utf-8"?><testsuite errors="1" failures="0" name="pytest" skipped="0" tests="1" time="3.370"><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File &quot;D:\python\Python\Python37-32\lib\site-packages\_pytest\main.py&quot;, line 213, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;D:\python\Python\Python37-32\lib\site-packages\_pytest\main.py&quot;, line 257, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\hooks.py&quot;, line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\manager.py&quot;, line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\manager.py&quot;, line 81, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\_pytest\main.py&quot;, line 278, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\hooks.py&quot;, line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\manager.py&quot;, line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\manager.py&quot;, line 81, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pytest_rerunfailures.py&quot;, line 176, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\_pytest\runner.py&quot;, line 81, in runtestprotocol
    rep = call_and_report(item, &quot;setup&quot;, log)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\_pytest\runner.py&quot;, line 169, in call_and_report
    report = hook.pytest_runtest_makereport(item=item, call=call)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\hooks.py&quot;, line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\manager.py&quot;, line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\manager.py&quot;, line 81, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 203, in _multicall
    gen.send(outcome)
  File &quot;D:\pyautoTest\conftest.py&quot;, line 71, in pytest_runtest_makereport
    capture_screenshot(case_name)
  File &quot;D:\pyautoTest\conftest.py&quot;, line 118, in capture_screenshot
    driver.save_screenshot(image_dir)
NameError: name &apos;driver&apos; is not defined</error></testcase></testsuite>