<?xml version="1.0" encoding="utf-8"?><testsuite errors="1" failures="0" name="pytest" skipped="0" tests="5" time="49.183"><testcase classname="test_dir.test_baidu.TestSearch" file="test_dir\test_baidu.py" line="11" name="test_baidu_search_case" time="8.616"></testcase><testcase classname="test_dir.test_baidu.TestSearch" file="test_dir\test_baidu.py" line="28" name="test_baidu_search[case1]" time="2.552"></testcase><testcase classname="test_dir.test_baidu.TestSearch" file="test_dir\test_baidu.py" line="28" name="test_baidu_search[case2]" time="2.529"></testcase><testcase classname="test_dir.test_baidu.TestSearch" file="test_dir\test_baidu.py" line="28" name="test_baidu_search[case3]" time="2.557"></testcase><testcase time="30.619"></testcase><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File &quot;D:\python\Python\Python37-32\lib\site-packages\_pytest\main.py&quot;, line 213, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;D:\python\Python\Python37-32\lib\site-packages\_pytest\main.py&quot;, line 257, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\hooks.py&quot;, line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\manager.py&quot;, line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\manager.py&quot;, line 81, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\_pytest\main.py&quot;, line 278, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\hooks.py&quot;, line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\manager.py&quot;, line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\manager.py&quot;, line 81, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pytest_rerunfailures.py&quot;, line 176, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\_pytest\runner.py&quot;, line 87, in runtestprotocol
    reports.append(call_and_report(item, &quot;call&quot;, log))
  File &quot;D:\python\Python\Python37-32\lib\site-packages\_pytest\runner.py&quot;, line 169, in call_and_report
    report = hook.pytest_runtest_makereport(item=item, call=call)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\hooks.py&quot;, line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\manager.py&quot;, line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\manager.py&quot;, line 81, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;D:\python\Python\Python37-32\lib\site-packages\pluggy\callers.py&quot;, line 203, in _multicall
    gen.send(outcome)
  File &quot;D:\pyautoTest\conftest.py&quot;, line 71, in pytest_runtest_makereport
    capture_screenshot(case_name)
  File &quot;D:\pyautoTest\conftest.py&quot;, line 118, in capture_screenshot
    driver.save_screenshot(image_dir)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py&quot;, line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py&quot;, line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File &quot;D:\python\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py&quot;, line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode(&apos;ascii&apos;))
  File &quot;D:\python\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py&quot;, line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)[&apos;value&apos;]
  File &quot;D:\python\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py&quot;, line 321, in execute
    self.error_handler.check_response(response)
  File &quot;D:\python\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py&quot;, line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette</error></testcase></testsuite>